import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeDollarSign, CalendarClock, CircleCheck, CreditCard, Pencil, Plus, RefreshCcw, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { atualizarAssinatura, atualizarPlano, assinaturasQueryKey, criarAssinatura, criarPlano, listarAssinaturas, listarClientesAssinatura, listarPlanos, listarWebsitesAssinatura, planosQueryKey, type Assinatura, type AssinaturaInput, type AssinaturaStatus, type Plano, type PlanoInput } from "@/lib/assinaturas.query";

const statusOptions: { value: AssinaturaStatus | "todas"; label: string }[] = [
  { value: "todas", label: "Todos os status" }, { value: "ativa", label: "Ativa" }, { value: "pendente", label: "Pendente" },
  { value: "atrasada", label: "Atrasada" }, { value: "suspensa", label: "Suspensa" }, { value: "cancelada", label: "Cancelada" },
];
const money = (n: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(n) || 0);
const localDate = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const emptySub = { cliente_id: "", website_id: "", plano_id: "", valor: "", data_inicio: localDate(), proximo_vencimento: "", status: "pendente" as AssinaturaStatus, observacoes: "" };
const emptyPlan = { nome: "", descricao: "", valor_mensal: "", valor_anual: "", periodo_cobranca: "mensal" as "mensal" | "anual", ativo: true };

export function AssinaturasPage() {
  const qc = useQueryClient();
  const [tab, setTab] = useState<"assinaturas" | "planos">("assinaturas");
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<AssinaturaStatus | "todas">("todas");
  const [subOpen, setSubOpen] = useState(false); const [planOpen, setPlanOpen] = useState(false);
  const [editingSub, setEditingSub] = useState<Assinatura | null>(null); const [editingPlan, setEditingPlan] = useState<Plano | null>(null);
  const [subForm, setSubForm] = useState(emptySub); const [planForm, setPlanForm] = useState(emptyPlan);
  const subsQ = useQuery({ queryKey: assinaturasQueryKey, queryFn: listarAssinaturas, retry: false });
  const plansQ = useQuery({ queryKey: planosQueryKey, queryFn: listarPlanos, retry: false });
  const clientsQ = useQuery({ queryKey: ["assinaturas-clientes"], queryFn: listarClientesAssinatura, retry: false });
  const sitesQ = useQuery({ queryKey: ["assinaturas-websites", subForm.cliente_id], queryFn: () => listarWebsitesAssinatura(subForm.cliente_id || undefined), enabled: subOpen, retry: false });
  const rows = useMemo(() => (subsQ.data ?? []).filter(s => (filter === "todas" || s.status === filter) && `${s.cliente?.nome ?? ""} ${s.website?.nome ?? ""} ${s.plano?.nome ?? ""}`.toLowerCase().includes(search.trim().toLowerCase())), [subsQ.data, filter, search]);
  const active = (subsQ.data ?? []).filter(s => s.status === "ativa");
  const recurring = active.reduce((sum, s) => { const p = s.plano?.periodo_cobranca; return sum + Number(s.valor) / (p === "anual" ? 12 : 1); }, 0);
  const dueSoon = active.filter(s => { const delta = (new Date(`${s.proximo_vencimento}T00:00:00`).getTime() - new Date(`${localDate()}T00:00:00`).getTime()) / 86400000; return delta >= 0 && delta <= 30; }).length;

  const subMutation = useMutation({ mutationFn: (input: AssinaturaInput) => editingSub ? atualizarAssinatura(editingSub.id, input) : criarAssinatura(input), onSuccess: async () => { setSubOpen(false); setEditingSub(null); await qc.invalidateQueries({ queryKey: assinaturasQueryKey }); toast.success(editingSub ? "Assinatura atualizada." : "Assinatura cadastrada."); }, onError: e => toast.error(e instanceof Error ? e.message : "Não foi possível salvar a assinatura.") });
  const planMutation = useMutation({ mutationFn: (input: PlanoInput) => editingPlan ? atualizarPlano(editingPlan.id, input) : criarPlano(input), onSuccess: async () => { setPlanOpen(false); setEditingPlan(null); await qc.invalidateQueries({ queryKey: planosQueryKey }); toast.success(editingPlan ? "Plano atualizado." : "Plano criado."); }, onError: e => toast.error(e instanceof Error ? e.message : "Não foi possível salvar o plano.") });
  const startSub = () => { setEditingSub(null); setSubForm({ ...emptySub }); setSubOpen(true); };
  const editSub = (s: Assinatura) => { setEditingSub(s); setSubForm({ cliente_id: s.cliente_id, website_id: s.website_id, plano_id: s.plano_id, valor: String(s.valor), data_inicio: s.data_inicio, proximo_vencimento: s.proximo_vencimento, status: s.status, observacoes: s.observacoes ?? "" }); setSubOpen(true); };
  const startPlan = () => { setEditingPlan(null); setPlanForm({ ...emptyPlan }); setPlanOpen(true); };
  const editPlan = (p: Plano) => { setEditingPlan(p); setPlanForm({ nome: p.nome, descricao: p.descricao ?? "", valor_mensal: String(p.valor_mensal), valor_anual: String(p.valor_anual), periodo_cobranca: p.periodo_cobranca, ativo: p.ativo }); setPlanOpen(true); };
  const setSub = (k: keyof typeof emptySub, v: string) => setSubForm(prev => ({ ...prev, [k]: v }));
  const submitSub = (e: React.FormEvent) => { e.preventDefault(); if (!subForm.cliente_id || !subForm.website_id || !subForm.plano_id || Number(subForm.valor) < 0 || !subForm.data_inicio || !subForm.proximo_vencimento) { toast.error("Informe cliente, website, plano, valor e datas."); return; } if (subForm.proximo_vencimento < subForm.data_inicio) { toast.error("O próximo vencimento não pode ser anterior ao início."); return; } subMutation.mutate({ cliente_id: subForm.cliente_id, website_id: subForm.website_id, plano_id: subForm.plano_id, valor: Number(subForm.valor || 0), data_inicio: subForm.data_inicio, proximo_vencimento: subForm.proximo_vencimento, status: subForm.status, observacoes: subForm.observacoes.trim() || null }); };
  const submitPlan = (e: React.FormEvent) => { e.preventDefault(); if (!planForm.nome.trim() || Number(planForm.valor_mensal) < 0 || Number(planForm.valor_anual) < 0 || (!planForm.valor_mensal && !planForm.valor_anual)) { toast.error("Informe nome e pelo menos um valor válido para o plano."); return; } planMutation.mutate({ nome: planForm.nome.trim(), descricao: planForm.descricao.trim() || null, valor_mensal: Number(planForm.valor_mensal || 0), valor_anual: Number(planForm.valor_anual || 0), periodo_cobranca: planForm.periodo_cobranca, ativo: planForm.ativo }); };

  return <main id="main-content" className="flex-1 px-5 py-8 sm:px-7 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl">
    <div className="sm:flex sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Receita recorrente</p><h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">Assinaturas</h1><p className="mt-2 text-sm text-muted-foreground sm:text-base">Gerencie planos, recorrências e vencimentos dos serviços WEZA.</p></div><Button className="mt-5 sm:mt-0" onClick={tab === "planos" ? startPlan : startSub}><Plus/>{tab === "planos" ? "Novo plano" : "Nova assinatura"}</Button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={<RefreshCcw className="size-4 text-primary"/>} label="Assinaturas ativas" value={String(active.length)} hint="Recorrências em andamento"/><Metric icon={<BadgeDollarSign className="size-4 text-emerald-500"/>} label="Receita recorrente mensal" value={money(recurring)} hint="Estimativa mensal equivalente das ativas"/><Metric icon={<CalendarClock className="size-4 text-amber-500"/>} label="Vencimentos em 30 dias" value={String(dueSoon)} hint="Assinaturas ativas com vencimento próximo"/></div>
    <div className="mt-7 flex flex-wrap gap-2"><Button variant={tab === "assinaturas" ? "default" : "outline"} onClick={() => setTab("assinaturas")}><RefreshCcw className="mr-2 size-4"/>Assinaturas</Button><Button variant={tab === "planos" ? "default" : "outline"} onClick={() => setTab("planos")}><CreditCard className="mr-2 size-4"/>Planos ({plansQ.data?.length ?? 0})</Button></div>
    {tab === "assinaturas" ? <section className="mt-4 overflow-hidden rounded-xl border border-glass-border bg-surface-glass shadow-soft"><div className="grid gap-3 border-b border-glass-border p-4 sm:grid-cols-[minmax(0,1fr)_12rem]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="bg-surface-soft pl-9" placeholder="Buscar cliente, website ou plano..." value={search} onChange={e=>setSearch(e.target.value)} aria-label="Buscar assinaturas"/></div><select className="h-10 rounded-md border border-input bg-surface-soft px-3 text-sm" value={filter} onChange={e=>setFilter(e.target.value as AssinaturaStatus | "todas")} aria-label="Filtrar por status">{statusOptions.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></div>
      {subsQ.isError ? <ErrorState retry={()=>subsQ.refetch()}/> : subsQ.isLoading ? <Loading/> : rows.length === 0 ? <Empty icon={<RefreshCcw/>} title={(subsQ.data?.length ?? 0) === 0 ? "Nenhuma assinatura cadastrada" : "Nenhuma assinatura encontrada"} text={(subsQ.data?.length ?? 0) === 0 ? "Quando a WEZA fechar os primeiros contratos recorrentes, cadastre as assinaturas e acompanhe os vencimentos por aqui." : "Altere a busca ou o filtro para encontrar assinaturas."} action={startSub} actionLabel="Nova assinatura"/> : <div className="divide-y divide-glass-border">{rows.map(s=><article key={s.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{s.plano?.nome ?? "Plano"} · {s.website?.nome ?? "Website"}</h3><Status status={s.status}/></div><p className="mt-1 text-sm text-muted-foreground">{s.cliente?.nome ?? "Cliente"} · {s.plano?.periodo_cobranca === "anual" ? "Cobrança anual" : "Cobrança mensal"}</p><p className="mt-1 text-xs text-muted-foreground">Início {new Date(`${s.data_inicio}T12:00:00`).toLocaleDateString("pt-BR")} · Próximo vencimento {new Date(`${s.proximo_vencimento}T12:00:00`).toLocaleDateString("pt-BR")}</p></div><div className="flex items-center justify-between gap-4 sm:justify-end"><strong className="font-display text-lg">{money(Number(s.valor))}<span className="text-xs font-normal text-muted-foreground">/{s.plano?.periodo_cobranca === "anual" ? "ano" : "mês"}</span></strong><Button variant="outline" size="sm" onClick={()=>editSub(s)}><Pencil className="mr-1 size-3.5"/>Editar</Button></div></article>)}</div>}</section> : <section className="mt-4 overflow-hidden rounded-xl border border-glass-border bg-surface-glass shadow-soft">{plansQ.isError ? <ErrorState retry={()=>plansQ.refetch()}/> : plansQ.isLoading ? <Loading/> : !(plansQ.data?.length) ? <Empty icon={<CreditCard/>} title="Nenhum plano cadastrado" text="Crie os planos recorrentes da WEZA antes de associá-los às assinaturas dos clientes." action={startPlan} actionLabel="Criar primeiro plano"/> : <div className="divide-y divide-glass-border">{plansQ.data.map(p=><article key={p.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{p.nome}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${p.ativo ? "bg-emerald-500/10 text-emerald-500" : "bg-muted text-muted-foreground"}`}>{p.ativo ? "Ativo" : "Inativo"}</span></div>{p.descricao && <p className="mt-1 text-sm text-muted-foreground">{p.descricao}</p>}<p className="mt-1 text-sm text-muted-foreground">Mensal: {money(p.valor_mensal)} · Anual: {money(p.valor_anual)}</p></div><Button variant="outline" size="sm" onClick={()=>editPlan(p)}><Pencil className="mr-1 size-3.5"/>Editar</Button></article>)}</div>}</section>}
  </div>
  <Sheet open={subOpen} onOpenChange={setSubOpen}><SheetContent className="w-full overflow-y-auto border-glass-border bg-background sm:max-w-xl"><SheetHeader><SheetTitle className="font-display">{editingSub ? "Editar assinatura" : "Nova assinatura"}</SheetTitle><SheetDescription>Vincule um cliente, website e plano já cadastrados. Nenhuma cobrança será gerada automaticamente.</SheetDescription></SheetHeader><form onSubmit={submitSub} className="mt-6 space-y-4">
    <Field label="Cliente *"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={subForm.cliente_id} onChange={e=>{setSub("cliente_id",e.target.value);setSub("website_id","")}} disabled={clientsQ.isLoading || !(clientsQ.data?.length)}><option value="">Selecione um cliente</option>{(clientsQ.data ?? []).map(c=><option key={c.id} value={c.id}>{c.nome}{c.empresa ? ` · ${c.empresa}` : ""}</option>)}</select>{!clientsQ.isLoading && !clientsQ.data?.length && <p className="text-xs text-amber-500">Cadastre um cliente ativo no módulo Clientes antes de criar uma assinatura.</p>}</Field>
    <Field label="Website *"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={subForm.website_id} onChange={e=>setSub("website_id",e.target.value)} disabled={!subForm.cliente_id}><option value="">Selecione um website</option>{(sitesQ.data ?? []).map(w=><option key={w.id} value={w.id}>{w.nome}</option>)}</select>{subForm.cliente_id && !sitesQ.isLoading && !sitesQ.data?.length && <p className="text-xs text-amber-500">Este cliente ainda não possui websites cadastrados.</p>}</Field>
    <Field label="Plano *"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={subForm.plano_id} onChange={e=>{const id=e.target.value;const p=(plansQ.data ?? []).find(x=>x.id===id);setSub("plano_id",id);if(p)setSub("valor",String(p.periodo_cobranca==="anual" ? p.valor_anual : p.valor_mensal));}} disabled={!(plansQ.data?.some(p=>p.ativo))}><option value="">Selecione um plano ativo</option>{(plansQ.data ?? []).filter(p=>p.ativo).map(p=><option key={p.id} value={p.id}>{p.nome} · {p.periodo_cobranca === "anual" ? "Anual" : "Mensal"}</option>)}</select>{!plansQ.isLoading && !(plansQ.data?.some(p=>p.ativo)) && <p className="text-xs text-amber-500">Cadastre um plano ativo na aba Planos antes de criar uma assinatura.</p>}</Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Valor contratado (R$) *"><Input type="number" min="0" step="0.01" value={subForm.valor} onChange={e=>setSub("valor",e.target.value)} placeholder="0,00"/></Field><Field label="Status"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={subForm.status} onChange={e=>setSub("status",e.target.value)}>{statusOptions.filter(s=>s.value!=="todas").map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></Field><Field label="Data de início *"><Input type="date" value={subForm.data_inicio} onChange={e=>setSub("data_inicio",e.target.value)}/></Field><Field label="Próximo vencimento *"><Input type="date" min={subForm.data_inicio} value={subForm.proximo_vencimento} onChange={e=>setSub("proximo_vencimento",e.target.value)}/></Field></div>
    <Field label="Observações"><Textarea rows={3} value={subForm.observacoes} onChange={e=>setSub("observacoes",e.target.value)} placeholder="Condições contratadas, detalhes da recorrência..."/></Field><SheetFooter className="gap-2 pt-2"><Button type="button" variant="outline" onClick={()=>setSubOpen(false)} disabled={subMutation.isPending}>Cancelar</Button><Button type="submit" disabled={subMutation.isPending || !clientsQ.data?.length || !plansQ.data?.some(p=>p.ativo)}>{subMutation.isPending ? "Salvando..." : "Salvar assinatura"}</Button></SheetFooter>
  </form></SheetContent></Sheet>
  <Sheet open={planOpen} onOpenChange={setPlanOpen}><SheetContent className="w-full overflow-y-auto border-glass-border bg-background sm:max-w-xl"><SheetHeader><SheetTitle className="font-display">{editingPlan ? "Editar plano" : "Novo plano"}</SheetTitle><SheetDescription>Configure valores e período de cobrança para os serviços recorrentes.</SheetDescription></SheetHeader><form onSubmit={submitPlan} className="mt-6 space-y-4"><Field label="Nome do plano *"><Input value={planForm.nome} onChange={e=>setPlanForm(p=>({...p,nome:e.target.value}))} placeholder="Ex.: Manutenção Essencial"/></Field><Field label="Descrição"><Textarea rows={3} value={planForm.descricao} onChange={e=>setPlanForm(p=>({...p,descricao:e.target.value}))} placeholder="Serviços incluídos no plano..."/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Valor mensal (R$)"><Input type="number" min="0" step="0.01" value={planForm.valor_mensal} onChange={e=>setPlanForm(p=>({...p,valor_mensal:e.target.value}))} placeholder="0,00"/></Field><Field label="Valor anual (R$)"><Input type="number" min="0" step="0.01" value={planForm.valor_anual} onChange={e=>setPlanForm(p=>({...p,valor_anual:e.target.value}))} placeholder="0,00"/></Field></div><Field label="Período padrão de cobrança"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={planForm.periodo_cobranca} onChange={e=>setPlanForm(p=>({...p,periodo_cobranca:e.target.value as "mensal"|"anual"}))}><option value="mensal">Mensal</option><option value="anual">Anual</option></select></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={planForm.ativo} onChange={e=>setPlanForm(p=>({...p,ativo:e.target.checked}))}/>Plano ativo e disponível para novas assinaturas</label><SheetFooter className="gap-2 pt-2"><Button type="button" variant="outline" onClick={()=>setPlanOpen(false)} disabled={planMutation.isPending}>Cancelar</Button><Button type="submit" disabled={planMutation.isPending}>{planMutation.isPending ? "Salvando..." : "Salvar plano"}</Button></SheetFooter></form></SheetContent></Sheet>
  </main>;
}
function Metric({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string}) { return <div className="rounded-xl border border-glass-border bg-surface-glass p-5 shadow-soft"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p>{icon}</div><p className="mt-3 font-display text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block space-y-1.5 text-sm font-medium">{label}{children}</label>; }
function Status({status}:{status:AssinaturaStatus}) { const label=statusOptions.find(s=>s.value===status)?.label ?? status; const cls:Record<AssinaturaStatus,string>={ativa:"bg-emerald-500/10 text-emerald-500",pendente:"bg-blue-500/10 text-blue-500",atrasada:"bg-amber-500/10 text-amber-500",suspensa:"bg-orange-500/10 text-orange-500",cancelada:"bg-muted text-muted-foreground"}; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${cls[status]}`}>{label}</span>; }
function Loading(){return <div className="p-12 text-center text-sm text-muted-foreground">Carregando dados...</div>;}
function ErrorState({retry}:{retry:()=>void}){return <div className="p-10 text-center" role="alert"><p>Não foi possível carregar os dados.</p><Button variant="outline" className="mt-4" onClick={retry}>Tentar novamente</Button></div>;}
function Empty({icon,title,text,action,actionLabel}:{icon:React.ReactNode;title:string;text:string;action:()=>void;actionLabel:string}){return <div className="grid min-h-80 place-items-center p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-lg bg-primary/10 text-primary">{icon}</span><h2 className="mt-4 font-display text-lg font-bold">{title}</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">{text}</p><Button className="mt-5" onClick={action}><Plus/>{actionLabel}</Button></div></div>;}
