import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeDollarSign, CalendarDays, CircleCheck, FileText, Pencil, Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { atualizarFaturamento, criarFaturamento, faturamentosQueryKey, listarAssinaturasFaturamento, listarClientesFaturamento, listarFaturamentos, type Faturamento, type FaturamentoInput, type FaturamentoStatus } from "@/lib/faturamentos.query";

const statuses: { value: FaturamentoStatus | "todos"; label: string }[] = [
  { value: "todos", label: "Todos os status" }, { value: "pendente", label: "Pendente" },
  { value: "pago", label: "Pago" }, { value: "atrasado", label: "Atrasado" }, { value: "cancelado", label: "Cancelado" },
];
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value) || 0);
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const currentMonth = () => today().slice(0, 7);
const blank = { cliente_id: "", assinatura_id: "", competencia: currentMonth(), valor: "", data_vencimento: today(), data_pagamento: "", status: "pendente" as FaturamentoStatus, observacoes: "" };
const monthLabel = (value: string) => { if (!value) return "—"; const [y,m] = value.slice(0,7).split("-"); return `${m}/${y}`; };

export function FaturamentoPage() {
  const qc = useQueryClient();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<FaturamentoStatus | "todos">("todos");
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Faturamento | null>(null);
  const [form, setForm] = useState(blank);
  const recordsQ = useQuery({ queryKey: faturamentosQueryKey, queryFn: listarFaturamentos, retry: false });
  const clientsQ = useQuery({ queryKey: ["faturamento-clientes"], queryFn: listarClientesFaturamento, retry: false });
  const subsQ = useQuery({ queryKey: ["faturamento-assinaturas", form.cliente_id], queryFn: () => listarAssinaturasFaturamento(form.cliente_id || undefined), enabled: open && !!form.cliente_id, retry: false });
  const records = recordsQ.data ?? [];
  const rows = useMemo(() => records.filter(f => (filter === "todos" || f.status === filter) && `${f.cliente?.nome ?? ""} ${f.cliente?.empresa ?? ""} ${f.competencia} ${f.assinatura ? "assinatura recorrente" : "avulso"}`.toLowerCase().includes(search.toLowerCase().trim())), [records, filter, search]);
  const paid = records.filter(f => f.status === "pago").reduce((sum,f)=>sum+Number(f.valor),0);
  const openAmount = records.filter(f => f.status === "pendente" || f.status === "atrasado").reduce((sum,f)=>sum+Number(f.valor),0);
  const overdue = records.filter(f => f.status !== "pago" && f.status !== "cancelado" && f.data_vencimento < today()).length;
  const mutation = useMutation({
    mutationFn: (input: FaturamentoInput) => editing ? atualizarFaturamento(editing.id,input) : criarFaturamento(input),
    onSuccess: async () => { setOpen(false); setEditing(null); await qc.invalidateQueries({queryKey:faturamentosQueryKey}); toast.success(editing ? "Faturamento atualizado." : "Faturamento registrado."); },
    onError: e => toast.error(e instanceof Error ? e.message : "Não foi possível salvar o faturamento."),
  });
  const startCreate = () => { setEditing(null); setForm({...blank}); setOpen(true); };
  const startEdit = (f: Faturamento) => { setEditing(f); setForm({cliente_id:f.cliente_id, assinatura_id:f.assinatura_id??"", competencia:f.competencia, valor:String(f.valor), data_vencimento:f.data_vencimento, data_pagamento:f.data_pagamento??"", status:f.status, observacoes:f.observacoes??""}); setOpen(true); };
  const set = (key: keyof typeof blank, value: string) => setForm(prev=>({...prev,[key]:value}));
  const setStatus = (value: FaturamentoStatus) => { set("status",value); if(value === "pago" && !form.data_pagamento) set("data_pagamento",today()); if(value !== "pago") set("data_pagamento",""); };
  const submit = (e: React.FormEvent) => { e.preventDefault(); if(!form.cliente_id || !/^\d{4}-\d{2}$/.test(form.competencia) || !form.valor.trim() || !Number.isFinite(Number(form.valor)) || Number(form.valor)<0 || !form.data_vencimento || (form.status === "pago" && !form.data_pagamento)) { toast.error("Informe cliente, competência, valor válido, vencimento e data de pagamento quando estiver pago."); return; }
    mutation.mutate({cliente_id:form.cliente_id, assinatura_id:form.assinatura_id||null, competencia:`${form.competencia}-01`, valor:Number(form.valor), data_vencimento:form.data_vencimento, data_pagamento:form.status === "pago" ? (form.data_pagamento||today()) : null, status:form.status, observacoes:form.observacoes.trim()||null}); };

  return <main id="main-content" className="flex-1 px-5 py-8 sm:px-7 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl">
    <div className="sm:flex sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Financeiro</p><h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">Faturamento</h1><p className="mt-2 text-sm text-muted-foreground sm:text-base">Centralize competências, valores faturados e situação dos recebimentos da WEZA.</p></div><Button className="mt-5 sm:mt-0" onClick={startCreate}><Plus/>Novo faturamento</Button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<FileText className="size-4 text-primary"/>} label="Faturamentos" value={String(records.length)} hint="Registros no histórico"/><Metric icon={<CircleCheck className="size-4 text-emerald-500"/>} label="Recebido" value={money(paid)} hint="Total marcado como pago"/><Metric icon={<BadgeDollarSign className="size-4 text-primary"/>} label="Em aberto" value={money(openAmount)} hint="Pendentes e atrasados"/><Metric icon={<CalendarDays className="size-4 text-amber-500"/>} label="Vencidos" value={String(overdue)} hint="Registros com vencimento passado"/></div>
    <section className="mt-7 overflow-hidden rounded-xl border border-glass-border bg-surface-glass shadow-soft"><div className="grid gap-3 border-b border-glass-border p-4 sm:grid-cols-[minmax(0,1fr)_12rem]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="bg-surface-soft pl-9" placeholder="Buscar cliente ou competência..." value={search} onChange={e=>setSearch(e.target.value)} aria-label="Buscar faturamentos"/></div><select className="h-10 rounded-md border border-input bg-surface-soft px-3 text-sm" value={filter} onChange={e=>setFilter(e.target.value as FaturamentoStatus|"todos")} aria-label="Filtrar faturamentos por status">{statuses.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></div>
    {recordsQ.isError ? <div className="p-10 text-center" role="alert"><p>Não foi possível carregar os faturamentos.</p><Button variant="outline" className="mt-4" onClick={()=>recordsQ.refetch()}>Tentar novamente</Button></div> : recordsQ.isLoading ? <div className="p-12 text-center text-sm text-muted-foreground">Carregando faturamentos...</div> : rows.length===0 ? <div className="grid min-h-80 place-items-center p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-lg bg-primary/10 text-primary"><FileText/></span><h2 className="mt-4 font-display text-lg font-bold">{records.length===0?"Nenhum faturamento cadastrado":"Nenhum faturamento encontrado"}</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">{records.length===0?"Registre os faturamentos dos serviços e contratos da WEZA. Os lançamentos não geram cobranças nem pagamentos automaticamente.":"Tente alterar a busca ou o filtro selecionado."}</p><Button className="mt-5" onClick={startCreate}><Plus>Novo faturamento</Plus></Button></div></div> : <div className="divide-y divide-glass-border">{rows.map(f=><article key={f.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{f.cliente?.nome??"Cliente"}</h3><Status status={f.status}/></div><p className="mt-1 text-sm text-muted-foreground">Competência {monthLabel(f.competencia)} · {f.assinatura?"Vinculado a assinatura":"Faturamento avulso"}</p><p className="mt-1 text-xs text-muted-foreground">Vencimento: {new Date(`${f.data_vencimento}T12:00:00`).toLocaleDateString("pt-BR")}{f.data_pagamento?` · Pago em ${new Date(`${f.data_pagamento}T12:00:00`).toLocaleDateString("pt-BR")}`:""}</p></div><div className="flex items-center justify-between gap-4 sm:justify-end"><strong className="font-display text-lg">{money(Number(f.valor))}</strong><Button variant="outline" size="sm" onClick={()=>startEdit(f)}><Pencil className="mr-1 size-3.5"/>Editar</Button></div></article>)}</div>}</section>
  </div>
  <Sheet open={open} onOpenChange={setOpen}><SheetContent className="w-full overflow-y-auto border-glass-border bg-background sm:max-w-xl"><SheetHeader><SheetTitle className="font-display">{editing?"Editar faturamento":"Novo faturamento"}</SheetTitle><SheetDescription>Registre um valor faturado por competência. Este lançamento não cria pagamento nem envia cobrança automaticamente.</SheetDescription></SheetHeader>
    <form onSubmit={submit} className="mt-6 space-y-4"><Field label="Cliente *"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.cliente_id} onChange={e=>{set("cliente_id",e.target.value);set("assinatura_id","")}} disabled={clientsQ.isLoading||!(clientsQ.data?.length)}><option value="">Selecione um cliente</option>{(clientsQ.data??[]).map(c=><option key={c.id} value={c.id}>{c.nome}{c.empresa?` · ${c.empresa}`:""}</option>)}</select>{!clientsQ.isLoading&&!clientsQ.data?.length&&<p className="text-xs text-amber-500">Cadastre um cliente ativo no módulo Clientes antes de registrar um faturamento.</p>}</Field>
    <Field label="Assinatura relacionada (opcional)"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.assinatura_id} onChange={e=>set("assinatura_id",e.target.value)} disabled={!form.cliente_id}><option value="">Faturamento avulso / sem assinatura</option>{(subsQ.data??[]).map(s=><option key={s.id} value={s.id}>Assinatura · {money(Number(s.valor))} · {s.status}</option>)}</select></Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Competência *"><Input type="month" value={form.competencia} onChange={e=>set("competencia",e.target.value)}/></Field><Field label="Valor (R$) *"><Input type="number" min="0" step="0.01" value={form.valor} onChange={e=>set("valor",e.target.value)} placeholder="0,00"/></Field><Field label="Data de vencimento *"><Input type="date" value={form.data_vencimento} onChange={e=>set("data_vencimento",e.target.value)}/></Field><Field label="Data do pagamento"><Input type="date" value={form.data_pagamento} onChange={e=>set("data_pagamento",e.target.value)} disabled={form.status!=="pago"}/></Field></div>
    <Field label="Status"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.status} onChange={e=>setStatus(e.target.value as FaturamentoStatus)}>{statuses.filter(s=>s.value!=="todos").map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></Field>
    <Field label="Observações"><Textarea rows={3} value={form.observacoes} onChange={e=>set("observacoes",e.target.value)} placeholder="Detalhes do faturamento, serviço ou competência..."/></Field>
    <SheetFooter className="gap-2 pt-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)} disabled={mutation.isPending}>Cancelar</Button><Button type="submit" disabled={mutation.isPending||!clientsQ.data?.length}>{mutation.isPending?"Salvando...":"Salvar faturamento"}</Button></SheetFooter></form>
  </SheetContent></Sheet></main>;
}
function Metric({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string}) { return <div className="rounded-xl border border-glass-border bg-surface-glass p-5 shadow-soft"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p>{icon}</div><p className="mt-3 font-display text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block space-y-1.5 text-sm font-medium">{label}{children}</label>; }
function Status({status}:{status:FaturamentoStatus}) { const label=statuses.find(s=>s.value===status)?.label??status; const cls:Record<FaturamentoStatus,string>={pendente:"bg-amber-500/10 text-amber-500",pago:"bg-emerald-500/10 text-emerald-500",atrasado:"bg-destructive/10 text-destructive",cancelado:"bg-muted text-muted-foreground"}; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${cls[status]}`}>{label}</span>; }
