import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeDollarSign, CalendarDays, CircleCheck, CreditCard, Pencil, Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { atualizarPagamento, criarPagamento, listarAssinaturasPagamento, listarClientesPagamento, listarFaturamentosPagamento, listarPagamentos, pagamentosQueryKey, type Pagamento, type PagamentoInput, type PagamentoStatus } from "@/lib/pagamentos.query";

const statuses: { value: PagamentoStatus | "todos"; label: string }[] = [
  { value: "todos", label: "Todos os status" }, { value: "pendente", label: "Pendente" },
  { value: "pago", label: "Pago" }, { value: "atrasado", label: "Atrasado" }, { value: "cancelado", label: "Cancelado" },
];
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value) || 0);
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const effectiveStatus = (p: Pagamento, date = today()): PagamentoStatus => p.status !== "pago" && p.status !== "cancelado" && p.data_vencimento < date ? "atrasado" : p.status;
const blank = { cliente_id: "", assinatura_id: "", faturamento_id: "", valor: "", data_vencimento: today(), data_pagamento: "", status: "pendente" as PagamentoStatus, metodo_pagamento: "", referencia: "", observacoes: "" };
const monthLabel = (value: string) => { if (!value) return "—"; const [y,m] = value.slice(0,7).split("-"); return `${m}/${y}`; };

export function PagamentosPage() {
  const qc = useQueryClient();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<PagamentoStatus | "todos">("todos");
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Pagamento | null>(null);
  const [form, setForm] = useState(blank);
  const paymentsQ = useQuery({ queryKey: pagamentosQueryKey, queryFn: listarPagamentos, retry: false });
  const clientsQ = useQuery({ queryKey: ["pagamentos-clientes"], queryFn: listarClientesPagamento, retry: false });
  const subsQ = useQuery({ queryKey: ["pagamentos-assinaturas", form.cliente_id], queryFn: () => listarAssinaturasPagamento(form.cliente_id || undefined), enabled: open && !!form.cliente_id, retry: false });
  const invoicesQ = useQuery({ queryKey: ["pagamentos-faturamentos", form.cliente_id], queryFn: () => listarFaturamentosPagamento(form.cliente_id || undefined), enabled: open && !!form.cliente_id, retry: false });
  const rows = useMemo(() => (paymentsQ.data ?? []).filter(p => (filter === "todos" || effectiveStatus(p) === filter) && `${p.cliente?.nome ?? ""} ${p.referencia ?? ""} ${p.metodo_pagamento ?? ""}`.toLowerCase().includes(search.toLowerCase().trim())), [paymentsQ.data, filter, search]);
  const totalPaid = (paymentsQ.data ?? []).filter(p=>p.status === "pago").reduce((s,p)=>s+Number(p.valor),0);
  const openAmount = (paymentsQ.data ?? []).filter(p=>["pendente", "atrasado"].includes(effectiveStatus(p))).reduce((s,p)=>s+Number(p.valor),0);
  const overdue = (paymentsQ.data ?? []).filter(p=>effectiveStatus(p) === "atrasado").length;
  const mutation = useMutation({
    mutationFn: (input: PagamentoInput) => editing ? atualizarPagamento(editing.id,input) : criarPagamento(input),
    onSuccess: async () => { setOpen(false); setEditing(null); await Promise.all([qc.invalidateQueries({queryKey:pagamentosQueryKey}), qc.invalidateQueries({queryKey:["faturamentos"]}), qc.invalidateQueries({queryKey:["dashboard"]})]); toast.success(editing ? "Pagamento atualizado." : "Pagamento registrado."); },
    onError: e => toast.error(e instanceof Error ? e.message : "Não foi possível salvar o pagamento."),
  });
  const startCreate = () => { setEditing(null); setForm({...blank}); setOpen(true); };
  const startEdit = (p: Pagamento) => { setEditing(p); setForm({cliente_id:p.cliente_id, assinatura_id:p.assinatura_id??"", faturamento_id:p.faturamento_id??"", valor:String(p.valor), data_vencimento:p.data_vencimento, data_pagamento:p.data_pagamento??"", status:p.status, metodo_pagamento:p.metodo_pagamento??"", referencia:p.referencia??"", observacoes:p.observacoes??""}); setOpen(true); };
  const set = (key: keyof typeof blank, value: string) => setForm(prev=>({...prev,[key]:value}));
  const setStatus = (value: PagamentoStatus) => { set("status",value); if(value === "pago" && !form.data_pagamento) set("data_pagamento",today()); if(value !== "pago") set("data_pagamento",""); };
  const selectInvoice = (id: string) => {
    set("faturamento_id", id);
    const invoice = (invoicesQ.data ?? []).find(f => f.id === id);
    if (invoice) {
      set("assinatura_id", invoice.assinatura_id ?? "");
      set("valor", String(invoice.valor));
      set("data_vencimento", invoice.data_vencimento);
    }
  };
  const submit = (e: React.FormEvent) => { e.preventDefault(); if(!form.cliente_id || !form.valor.trim() || !Number.isFinite(Number(form.valor)) || Number(form.valor)<0 || !form.data_vencimento || (form.status === "pago" && !form.data_pagamento)) { toast.error("Informe cliente, valor válido, vencimento e a data de pagamento quando estiver pago."); return; }
    mutation.mutate({cliente_id:form.cliente_id, assinatura_id:form.assinatura_id||null, faturamento_id:form.faturamento_id||null, valor:Number(form.valor), data_vencimento:form.data_vencimento, data_pagamento:form.status === "pago" ? (form.data_pagamento||today()) : null, status:form.status, metodo_pagamento:form.metodo_pagamento.trim()||null, referencia:form.referencia.trim()||null, observacoes:form.observacoes.trim()||null}); };

  return <main id="main-content" className="flex-1 px-5 py-8 sm:px-7 lg:px-8 lg:py-10"><div className="mx-auto max-w-7xl">
    <div className="sm:flex sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Financeiro</p><h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">Pagamentos</h1><p className="mt-2 text-sm text-muted-foreground sm:text-base">Acompanhe recebimentos, vencimentos e valores em aberto da WEZA.</p></div><Button className="mt-5 sm:mt-0" onClick={startCreate}><Plus/>Novo pagamento</Button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CreditCard className="size-4 text-primary"/>} label="Registros" value={String(paymentsQ.data?.length??0)} hint="Pagamentos cadastrados"/><Metric icon={<CircleCheck className="size-4 text-emerald-500"/>} label="Recebido" value={money(totalPaid)} hint="Total com status pago"/><Metric icon={<BadgeDollarSign className="size-4 text-primary"/>} label="Em aberto" value={money(openAmount)} hint="Pendentes e atrasados"/><Metric icon={<CalendarDays className="size-4 text-amber-500"/>} label="Vencidos" value={String(overdue)} hint="Não pagos com vencimento passado"/></div>
    <section className="mt-7 overflow-hidden rounded-xl border border-glass-border bg-surface-glass shadow-soft"><div className="grid gap-3 border-b border-glass-border p-4 sm:grid-cols-[minmax(0,1fr)_12rem]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="bg-surface-soft pl-9" placeholder="Buscar cliente, referência ou método..." value={search} onChange={e=>setSearch(e.target.value)} aria-label="Buscar pagamentos"/></div><select className="h-10 rounded-md border border-input bg-surface-soft px-3 text-sm" value={filter} onChange={e=>setFilter(e.target.value as PagamentoStatus|"todos")} aria-label="Filtrar pagamentos por status">{statuses.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></div>
    {paymentsQ.isError ? <div className="p-10 text-center" role="alert"><p>Não foi possível carregar os pagamentos.</p><Button variant="outline" className="mt-4" onClick={()=>paymentsQ.refetch()}>Tentar novamente</Button></div> : paymentsQ.isLoading ? <div className="p-12 text-center text-sm text-muted-foreground">Carregando pagamentos...</div> : rows.length===0 ? <div className="grid min-h-80 place-items-center p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-lg bg-primary/10 text-primary"><CreditCard/></span><h2 className="mt-4 font-display text-lg font-bold">{(paymentsQ.data?.length??0)===0?"Nenhum pagamento cadastrado":"Nenhum pagamento encontrado"}</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">{(paymentsQ.data?.length??0)===0?"Quando a WEZA começar a receber, registre os pagamentos e acompanhe vencimentos e recebimentos por aqui.":"Tente alterar a busca ou o filtro selecionado."}</p><Button className="mt-5" onClick={startCreate}><Plus/>Novo pagamento</Button></div></div> : <div className="divide-y divide-glass-border">{rows.map(p=><article key={p.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{p.cliente?.nome??"Cliente"}</h3><Status status={effectiveStatus(p)}/></div><p className="mt-1 text-sm text-muted-foreground">{p.faturamento_id?"Pagamento vinculado a faturamento":p.assinatura?"Pagamento vinculado a uma assinatura":"Pagamento avulso"}{p.referencia?` · ${p.referencia}`:""}{p.metodo_pagamento?` · ${p.metodo_pagamento}`:""}</p><p className="mt-1 text-xs text-muted-foreground">Vencimento: {new Date(`${p.data_vencimento}T12:00:00`).toLocaleDateString("pt-BR")}{p.data_pagamento?` · Pago em ${new Date(`${p.data_pagamento}T12:00:00`).toLocaleDateString("pt-BR")}`:""}</p></div><div className="flex items-center justify-between gap-4 sm:justify-end"><strong className="font-display text-lg">{money(Number(p.valor))}</strong><Button variant="outline" size="sm" onClick={()=>startEdit(p)}><Pencil className="mr-1 size-3.5"/>Editar</Button></div></article>)}</div>}</section>
  </div>
  <Sheet open={open} onOpenChange={setOpen}><SheetContent className="w-full overflow-y-auto border-glass-border bg-background sm:max-w-xl"><SheetHeader><SheetTitle className="font-display">{editing?"Editar pagamento":"Novo pagamento"}</SheetTitle><SheetDescription>Registre um recebimento ou valor a receber. Ao vincular um faturamento, o status e a data de pagamento serão sincronizados automaticamente.</SheetDescription></SheetHeader>
    <form onSubmit={submit} className="mt-6 space-y-4"><Field label="Cliente *"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.cliente_id} onChange={e=>{set("cliente_id",e.target.value);set("assinatura_id","");set("faturamento_id","")}} disabled={clientsQ.isLoading||!(clientsQ.data?.length)}><option value="">Selecione um cliente</option>{(clientsQ.data??[]).map(c=><option key={c.id} value={c.id}>{c.nome}{c.empresa?` · ${c.empresa}`:""}</option>)}</select>{!clientsQ.isLoading&&!clientsQ.data?.length&&<p className="text-xs text-amber-500">Cadastre um cliente ativo no módulo Clientes antes de registrar um pagamento.</p>}</Field>
    <Field label="Faturamento relacionado (opcional)"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.faturamento_id} onChange={e=>selectInvoice(e.target.value)} disabled={!form.cliente_id||invoicesQ.isLoading}><option value="">Pagamento avulso / sem faturamento</option>{(invoicesQ.data??[]).filter(f=>f.status!=="pago"||f.id===form.faturamento_id).map(f=><option key={f.id} value={f.id}>Comp. {monthLabel(f.competencia)} · {money(Number(f.valor))} · vence {new Date(`${f.data_vencimento}T12:00:00`).toLocaleDateString("pt-BR")} · {f.status}</option>)}</select><p className="text-xs text-muted-foreground">Selecione a fatura exata. O vínculo impede que outro faturamento do mesmo cliente seja alterado por engano.</p></Field>
    <Field label="Assinatura relacionada (opcional)"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.assinatura_id} onChange={e=>set("assinatura_id",e.target.value)} disabled={!form.cliente_id||!!form.faturamento_id}><option value="">Pagamento avulso / sem assinatura</option>{(subsQ.data??[]).map(s=><option key={s.id} value={s.id}>Assinatura · {money(Number(s.valor))} · {s.status}</option>)}</select></Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Valor (R$) *"><Input type="number" min="0" step="0.01" value={form.valor} onChange={e=>set("valor",e.target.value)} placeholder="0,00"/></Field><Field label="Forma de pagamento"><Input value={form.metodo_pagamento} onChange={e=>set("metodo_pagamento",e.target.value)} placeholder="Pix, cartão, transferência..."/></Field><Field label="Data de vencimento *"><Input type="date" value={form.data_vencimento} onChange={e=>set("data_vencimento",e.target.value)}/></Field><Field label="Data do pagamento"><Input type="date" value={form.data_pagamento} onChange={e=>set("data_pagamento",e.target.value)} disabled={form.status!=="pago"}/></Field></div>
    <Field label="Status"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.status} onChange={e=>setStatus(e.target.value as PagamentoStatus)}>{statuses.filter(s=>s.value!=="todos").map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></Field>
    <Field label="Referência"><Input value={form.referencia} onChange={e=>set("referencia",e.target.value)} placeholder="Ex.: Mensalidade setembro / fatura #..."/></Field><Field label="Observações"><Textarea rows={3} value={form.observacoes} onChange={e=>set("observacoes",e.target.value)} placeholder="Detalhes internos do recebimento..."/></Field>
    <SheetFooter className="gap-2 pt-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)} disabled={mutation.isPending}>Cancelar</Button><Button type="submit" disabled={mutation.isPending||!clientsQ.data?.length}>{mutation.isPending?"Salvando...":"Salvar pagamento"}</Button></SheetFooter></form>
  </SheetContent></Sheet></main>;
}
function Metric({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string}) { return <div className="rounded-xl border border-glass-border bg-surface-glass p-5 shadow-soft"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p>{icon}</div><p className="mt-3 font-display text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block space-y-1.5 text-sm font-medium">{label}{children}</label>; }
function Status({status}:{status:PagamentoStatus}) { const label=statuses.find(s=>s.value===status)?.label??status; const cls:Record<PagamentoStatus,string>={pendente:"bg-amber-500/10 text-amber-500",pago:"bg-emerald-500/10 text-emerald-500",atrasado:"bg-destructive/10 text-destructive",cancelado:"bg-muted text-muted-foreground"}; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${cls[status]}`}>{label}</span>; }
